### ISSUE TITLE
1.0.5 Status Bar text for some of the Properties controls appears to be missing.

### ISSUE THREAD

**Issue by worblyhead** [Nornec/Midinous-Issues#10]
If I select a control point in the Midinous canvas then the Properties pane for that control appears as expected.  However, if I hover over the controls that dictate how the order of a signal is propagated from the block then the Status Bar does not update for each control hovered over.  It appears the text that does appear is related to the Paths controls only.  If memory serves me correctly, this worked as expected in Ver 1.0.3.

1) Open a Midinous session and select a control point and NOTE that the Properties panel opens as expected.
2) In the Properties panel hover over one of the 4 "Order" controls in the top right corner and NOTE that the status bar text at the bottom of the UI does not update properly for the button hovered over (see attached screen cap)

<img width="960" alt="Midinous_Tooltip_statusbar_1" src="https://user-images.githubusercontent.com/115739648/195734165-58d6e849-8a24-4314-8545-e32013b0ec1a.png">

**Comment by worblyhead** [comment]
As a tangential aside some of the hover/Status Bar text behavior appears a bit inconsistent.  For example, if I hover over the "Note" label text or the Note edit boxes they all result in the Status Bar text being displayed.  However I can NOT hover over the Velocity, Channel, Duration, or Repeat text to get the same behavior.  Same with the text labels in the "Relative Changes" portion of the panel.   None of this is a show stopper, but just minor spit polish inconsistencies/

**Comment by Nornec** [comment]
Known issue. I simply haven't updated or added updated tooltips for new controls. Some tooltips are also tied to the wrong elements.

**Comment by Nornec** [comment]
Will be fixed in 1.1.6.0
