### ISSUE TITLE
1.0.5 - Midinous crashed after adding Midi primary point

### ISSUE THREAD

**Issue by worblyhead** [Nornec/Midinous-Issues#11]
While playing about with adding points in the Midinous canvas, the app crashed unexpectedly.  At the time of the crash I was simply adding a point to the canvas.  I have attached the error logs and the specific save file I was using.  Please NOTE that I had to change the json file extension to let GITHUB allow me to upload the file

Please rename 

Bash_1.txt

to 

Bash_1.json 

and place in appropriate save directory to use.

[log.txt](https://github.com/Nornec/Midinous-Issues/files/9785309/log.txt)
[log_error.txt](https://github.com/Nornec/Midinous-Issues/files/9785310/log_error.txt)
[log_full.txt](https://github.com/Nornec/Midinous-Issues/files/9785311/log_full.txt)
[Bash_1.txt](https://github.com/Nornec/Midinous-Issues/files/9785315/Bash_1.txt)

**Comment by worblyhead** [comment]
May be related to 

https://github.com/Nornec/Midinous-Issues/issues/6

For me simply loading Bash_1 and adding a point reproduces the crash every time.

**Comment by worblyhead** [comment]
Alternate repro steps

1) Open Midinous and add a point.
2) Save the session and quit out of Midinous.
3) Restart Midinous and File > Open the session saved in Step 2
4) Attempt to add a point to the canvas and NOTE Midinous crashes
5) Inspect log files at %localappdata%\Midinous

**Comment by Nornec** [comment]
I am aware of this issue. Issue #6
