### ISSUE TITLE
Enhancement - Add support for user Scala files 

### ISSUE THREAD

**Issue by worblyhead** [Nornec/Midinous-Issues#13]
Not sure what the roadmap is for Midinous user defined scale support, but adding the ability to load Scala files would allow users to not only add scales, but tunings as well (e.g. Just Intonation  etc.).  For more info, please see

https://www.huygens-fokker.org/scala/
https://www.huygens-fokker.org/scala/scl_format.html

**Comment by Nornec** [comment]
I don't think this will mesh well with the program, as I do not intend to support microtonal output (since the output is just midi). It doesn't really make sense to support it.

User scales will continue to be based on 12-tone equal temperament.
