### ISSUE TITLE
1.0.5 - Attempting to perform a Snapping on an unsnapped point results in confusing behavior

### ISSUE THREAD

**Issue by worblyhead** [Nornec/Midinous-Issues#14]
Not sure if the snapping operation is performing as designed, but I was trying to get get a point I placed randomly on the canvas to snap back to the grid when I enabled Snapping.  However this didn't appear to allow snapping to the visual grid.  When I tried to move the point, the point moved the distance of the visual grid points, but did not actually snap to the visual grid.

Repro steps
========
1) Open a New session in Midinous.
2) Turn OFF the "Snapping" option.
3) Place a point somewhere on the canvas, but NOT on the visual grid.
4) Turn ON the "Snapping" option
5) Attempt to move the point and NOTE that the point moves a delta distance corresponding to the delta distance between the Visible grid points.  However, the point does NOT snap to the visible grid points as I was expecting.

**Comment by Nornec** [comment]
This is expected behavior. If you want points to snap back to the grid, use the "quantize" button, or push alt (by default). This will move points that are not on the grid to the grid. I wanted to keep the delta movement the same for points or sequences not started on the grid.

**Comment by worblyhead** [comment]
Ah, good to know.  Maybe this sort of thing could be covered in the tutorial?

**Comment by Nornec** [comment]
Yes, the tutorial needs to be updated with many of the new features.
Currently it is woefully out of date.
