### ISSUE TITLE
Y axis inverted

### ISSUE THREAD

**Issue by BestGitHubUsername** [Nornec/Midinous-Issues#15]
1.1.0 Y coordinates are negative when above (y,0) according to the highlight bar at the bottom of the canvas

**Comment by Nornec** [comment]
In graphics, this is how coordinates are arranged. The upper left hand corner of an area is always 0,0 while positive X is to the right and positive Y is down. This is also how tables are read, with columns extending right, and rows extending down.

**Comment by BestGitHubUsername** [comment]
in that case where my confusion comes from, is that the canvas extends beyond x,0 y,0 like cartesian graphs in math, not like rulers in graphics and x,0 y,0 by default is the center of the canvas not the top left (when you open a new midinous document). but i can understand it now as expected behaviour
