### ISSUE TITLE
1.1.0 - Linux: Options do not save

### ISSUE THREAD

**Issue by dromer** [Nornec/Midinous-Issues#17]
Trying with the pre-release binary.

Any of the options that are changed during runtime are forgotten on the next startup.

**Comment by Nornec** [comment]
Can you check to make sure your **<user>/.local/share/Midinous/user** folder exists? This is where the settings.json file is stored. Can you also confirm that your settings file is there? The only time the settings are reset is when using the reset settings option or if the settings file doesn't exist or the settings folder doesn't exist. In both of these cases, however, the file should be created.

**Comment by dromer** [comment]
Both the folder and settings.json are there.

I can see the settings file change when I modify a key binding, but when I start up the program again the settings file is reset with the default value again.

**Comment by Nornec** [comment]
Thanks. I fixed this, but still having an issue with the reset settings option. Will leave this open since it seems related.

**Comment by Nornec** [comment]
The reset settings have been fixed now. The next release will contain the fix.
