### ISSUE TITLE
1.1.0 - Linux: cancel remap with esc doesn't cancel/escape

### ISSUE THREAD

**Issue by dromer** [Nornec/Midinous-Issues#18]
as the title says: I was mid-rebinding a key then wanted to cancel -> pressing escape doesn't cancel the procedure

**Comment by Nornec** [comment]
Interesting. Not observed on Windows -- will check which key escape registers as on Linux.

**Comment by Nornec** [comment]
Ok, so, on my Linux test box, The escape key registers as the same ID (27) and key name as on my Windows machine. I am also able to cancel key binding changes and change them as normal.

**Comment by dromer** [comment]
With the program `xev` the escape key looks like:
```
KeyPress event, serial 36, synthetic NO, window 0x1a00001,
    root 0x1dc, subw 0x1a00002, time 1053060, (43,39), root:(44,59),
    state 0x0, keycode 9 (keysym 0xff1b, Escape), same_screen YES,
    XLookupString gives 1 bytes: (1b) "
mbLookupString gives 1 bytes: (1b) "
FilterEvent returns: False

KeyRelease event, serial 36, synthetic NO, window 0x1a00001,
    root 0x1dc, subw 0x1a00002, time 1053092, (43,39), root:(44,59),
    state 0x0, keycode 9 (keysym 0xff1b, Escape), same_screen YES,
    XLookupString gives 1 bytes: (1b) "
FilterEvent returns: False
```

**Comment by dromer** [comment]
But, I just tested and `esc` cancels the dialog just fine.

So false alarm I guess :)
