### ISSUE TITLE
1.1.0 - Reordered paths don't save on reload

### ISSUE THREAD

**Issue by Marvai** [Nornec/Midinous-Issues#20]
If you reorder which paths are played first in round robin, the new order only lasts for the duration of the session. Upon exiting Midinous and restarting, and loading the previous save, path orders appear to revert to default.

**Comment by Nornec** [comment]
Can't reproduce. Please check issue persistence in upcoming release candidate. I tested this with Note points and CC points. Saved a file, closed the program, reopened the program, loaded, and configured path order was saved.
