### ISSUE TITLE
1.1.0 - Point Properties Not Saving Properly

### ISSUE THREAD

**Issue by Marvai** [Nornec/Midinous-Issues#21]
Unfortunately I cannot find a way to easily reproduce, but at times when loading a save where teleport points were muted, they would unmute. It may have been after deleting/redrawing paths, but some teleport points were not connected to any of the deleted/redrawn paths.

**Comment by BestGitHubUsername** [comment]
also, in a save document where none of these points are connected by Paths

muted Note Point and muted CC Point will not save mute status
Logic Points will not save Gate Type (all Logic Points load as AND)

**Comment by BestGitHubUsername** [comment]
adding to this here because i think it might be connected.

copy&pasting a [NOT] Logic Point will lose its [NOT] status

**Comment by Nornec** [comment]
Fixed in upcoming release candidate.
