### ISSUE TITLE
1.1.0 Logic LED (NOT)

### ISSUE THREAD

**Issue by BestGitHubUsername** [Nornec/Midinous-Issues#23]
(NOT) function of LED does not display the (NOT) indicator and does not act as (NOT)

the Logic Point LED in default mode remains OFF unless momentarily actioned by a Traveller or Logic switch, I would expect the (NOT) mode to remain ON under the same conditions but it does not.
also, does not have the central mark that indicates (NOT) mode consistant with all other Logic Points

**Comment by Nornec** [comment]
LEDs act as diodes and therefore NOT does not affect them. However the property is still configurable so if switching logic types, this property will carry over automatically. LEDs do not provide any output unless given any output.
