### ISSUE TITLE
1.1.0 Logic Points Not Saving Settings Between Copy & Save

### ISSUE THREAD

**Issue by BestGitHubUsername** [Nornec/Midinous-Issues#24]
in the attached save file. i built a NOR flip flop then copied the circuit. 
i had to reset the [NOT] state of the OR Points of the copy
the copy did not work as a flip flop
i saved and reopened the Canvas and had to reset all Logic Points [they all loaded as AND Points] 
then the copy circuit worked but the original did not 

[c_p flip flop broken .zip](https://github.com/Nornec/Midinous-Issues/files/9945794/c_p.flip.flop.broken.zip)

**Comment by Nornec** [comment]
Fixed in next release candidate.
