### ISSUE TITLE
1.1.0 Internal Synth & multiple MIDI Channels

### ISSUE THREAD

**Issue by BestGitHubUsername** [Nornec/Midinous-Issues#25]
the Internal Synth cannot handle multiple MIDI Channels per document. 
i don't know if this is a limitation of my pc or the software
if all the points are set to the same channel the playback is as expected (Sine sounds like Sine, Sawtooth like Sawtooth etc)

in this attached document i have built a 5 Point network 
each Point set to play a note on a separate Midi channel 1-5
each channel is set to Sine
most Points sound like a Sawtooth or buzzy Triangle

[midi channel test.zip](https://github.com/Nornec/Midinous-Issues/files/9947813/midi.channel.test.zip)

**Comment by Nornec** [comment]
Your save file sounded just fine to me. I would check your gain. I could not reproduce the issue.
