### ISSUE TITLE
1.1.0 - CC starting value is not stored or loaded on document save/load

### ISSUE THREAD

**Issue by ScreenPlane** [Nornec/Midinous-Issues#33]
In a CC the End Amount value (which is actually the starting value) of a slew is not stored (or not loaded). When loaded the value is always 0 and the values are gone.
Therefor the transition is always starting with 0 and going to the value of the Amount.

**Comment by ScreenPlane** [comment]
Most often the starting value for a transition (Slew) would be the current value. A check box with "use current value" would be a fast way for operating.  If a starting value is typed in it could use this particular value.

**Comment by ScreenPlane** [comment]
This most critical issue I still have with using Midinous is that the end value (actually the start value) of a cc is not written into the file. After a crash on the beta, it means putting them all back in manually. If the store/load function would be included, I could at least restore it to where I was. Thanks.

**Comment by Nornec** [comment]
Fixed in upcoming release candidate.

**Comment by ScreenPlane** [comment]
Hi Jay,
thanks, this sounds great. Is the new beta already up and running? I have just checked and it’s still listed as 1.1.0.

Best,
Sebastian

**Comment by Nornec** [comment]
Not yet. There will likely be an update out before the end of the weekend.
Please check Discord for more info.

**Comment by ScreenPlane** [comment]
Great, thanks for making it happen!



> Am 14.04.2023 um 22:31 schrieb Jay ***@***.***>:
> 
> 
> Not yet. There will likely be an update out before the end of the weekend.
> Please check Discord for more info.
>

**Comment by ScreenPlane** [comment]
Hi Jay,
storage of the CC starting values seems to work. Great! 

Just a suggestion: under slew mode it’s still namend as „end amount“. Might be good to change it to „starting value“ or „starting amount“.

Cheers



> Am 14.04.2023 um 22:31 schrieb Jay ***@***.***>:
> 
> 
> Not yet. There will likely be an update out before the end of the weekend.
> Please check Discord for more info.
>

**Comment by Nornec** [comment]
End Amount behaves as an actual end amount. Please let me know otherwise.

**Comment by ScreenPlane** [comment]
I see, yes, this is right. 

From the general feeling I would think amount is the value that should be reached, while slew is the transition to this value. Therefore having the starting value in slew, sounded right to me. 



> Am 16.04.2023 um 14:39 schrieb Jay ***@***.***>:
> 
> 
> End Amount behaves as an actual end amount. Please let me know otherwise.
>
