### ISSUE TITLE
File Management

### ISSUE THREAD

**Issue by ScreenPlane** [Nornec/Midinous-Issues#34]
Not a classical bug, but a serious request for professional use:

it should possible to delete or transfer sequence files. If a midi sequence belongs to a particular project it should possible to group it to a project folder. Sample files would be good, if stored in a sample folder. Hard to find a particular file if they are all in one folder. 

There must be a way to transfer files from one machine to the other. This is extremely difficult if the files are stored in a hidden folder. 

Please open the file structure, so files can be deleted, renamed, moved and transferred.

**Comment by Nornec** [comment]
I like the idea of samples/examples being in a separate folder and having a separate tab with these when loading. I can also include a button which should be able to open the directory in your host system. I will likely not handle any deleting of sequences from the program itself, but the button to view local files should be good enough for most people.

**Comment by ScreenPlane** [comment]
Sounds good. Thanks. Yes, if the local files will be accessible, I can delete them there. Sometimes I end up with 10 iterations before the final file, so it’s good to finally kill the non used ones.


The most critical issue I still have is that the end value (actually the start value) of a cc is not written into the file. After a crash on the beta, it means to start. I the store function would be included, I could at least restore it to where I was...

**Comment by Nornec** [comment]
See Issue #33

**Comment by Nornec** [comment]
Features added in 1.1.5.6
