### ISSUE TITLE
(Beta 1.05) Save files from Jay, Benn, Venus etc. are not available to open

### ISSUE THREAD

**Issue by worblyhead** [Nornec/Midinous-Issues#4]
I previously was running Ver 1.03 prior to checking out the Beta 1.05.  In 1.03, there were multiple save files from Jay, Benn, Venus etc. that do NOT appear to be available in 1.05

1) Open Beta 1.05
2) Navigate to File > Open and NOTE that the files available in 1.03 are no longer available in 1.05

On a tangential note, the file path for the Open and Save dialogs is not shown and there is no discernible way of browsing to an alternate file path location.

**Comment by Nornec** [comment]
The save file path is static. I have no plans to introduce a full file browser. It is to standardize cloud saving capabilities and makes loading documents a heck of a lot easier. As to why your saves didn't carry over. That's a mystery. I may need you to do a fresh install of 1.0.3 (after backing up your stuff) and trying 1.0.5 again. I included some logic to create new versions of saves when you first boot up the new version, but would be interesting to see what the log says after first startup in this instance.

**Comment by worblyhead** [comment]
1) I went back and installed 1.0.3.  
2) Upon opening Midinous, I verified that the ver was downgraded from 1.0.5 to 1.0.3
3) I went to File > Open and Benn's Jay's etc. files were indeed listed.
4) After closing Midinous, I went ahead an downloaded the Beta 1.0.5 version
5) After dismissing the tutorial splash page, I navigated to File > Open and Benn's, Jay's etc. files were NOT present.  
6) I closed Midinous
7) The log files (attached) do not appear to reveal anything in this regard 


BTW, which directory are the saved files suppose to be in?
[log.txt](https://github.com/Nornec/Midinous-Issues/files/9792094/log.txt)
[log_error.txt](https://github.com/Nornec/Midinous-Issues/files/9792095/log_error.txt)
[log_full.txt](https://github.com/Nornec/Midinous-Issues/files/9792096/log_full.txt)

**Comment by worblyhead** [comment]
I just fired up 1.1.0 and this issue still persists.

**Comment by Nornec** [comment]
The current package release doesn't contain these save files, which is why you didn't see them after the upgrade or a fresh install. The new version will have these in the download package and should be copied over to the save directory upon first load.

**Comment by Nornec** [comment]
1.1.5.0+ has these example files included in the download from Steam.
