### ISSUE TITLE
Point Probability input doesn't allow inputs properly

### ISSUE THREAD

**Issue by MHGray** [Nornec/Midinous-Issues#43]
Something is wonky with the inputs for the probability entry on points. If the entire value is selected and you press delete or try to overwrite it then instead it deselects the value and does nothing. 

![image](https://github.com/Nornec/Midinous-Issues/assets/8196735/cf3204a9-9e92-4213-8cf2-32fb5a753eb6)
In the above example, the previous probability is completely selected. If I then press '8' I would expect the "100" to be erased and replaced with an '8'. Instead the 100 becomes deselected and the cursor moves in between the 1 and left most 0. 

You can also try and erase the number by clicking the end and hitting back space, but doing that you cannot delete the last digit ('1' in the case of the default value of 100)

**Comment by Nornec** [comment]
Confirmed bug. Should work like the other SpinButtons but doesn't. I'll check it out.

**Comment by Nornec** [comment]
Fixed in 1.1.6.6
