### ISSUE TITLE
Pasting CC point data doesn't enable/disable slew mode and doesn't paste end amount

### ISSUE THREAD

**Issue by MHGray** [Nornec/Midinous-Issues#46]
When copying and pasting from one CC point to another, the slew mode toggle state isn't copied, and the end amount isn't copied. This is using the copy and paste buttons at the top of the properties window. 

I also noticed that using the undo command after pasting properties in this way does not actually get undone. Instead the last change before the paste gets undone. 

![image](https://github.com/Nornec/Midinous-Issues/assets/8196735/c1794cb3-e11e-4e41-98c4-8d5b9a812c86)

**Reproduce:** 
Make two CC points 1 and 2
On point 1 turn on slew mode and change the end amount to some number (we'll say 15)
On point 1, hit the copy data button at the top of the properties window
On point 2, click the paste data button at the top of the properties window
**Slew mode is not enabled**
Turn on slew mode manually
copy point 1 again
paste onto point 2
**the end amount has not been copied.**

**Comment by Nornec** [comment]
Confirmed bug. Thanks for the report.

**Comment by Nornec** [comment]
Fixed in 1.1.6.6.
This behavior also existed with some Note Point properties. That, too, has been rectified.
