### ISSUE TITLE
1.1.6.5 - Start Point toggle hotkey creates second traveler at all Start Points

### ISSUE THREAD

**Issue by MHGray** [Nornec/Midinous-Issues#47]
![image](https://github.com/Nornec/Midinous-Issues/assets/8196735/2f108e1f-a648-4ac9-8509-fa093a2e3fc3)

In the above example, there is only a single start point. If I do the following things:
1. Select Unrelated Note
2. Push 'i' on my keyboard (the toggle start point hotkey)
3. Press 'Space' on my keyboard (the begin playback hotkey)

Then when a traveler arrives at the point marked Sequential, two travelers emerge, one going up and one going right:
![image](https://github.com/Nornec/Midinous-Issues/assets/8196735/1adfaf2c-09e5-4fa2-8b37-8e7199acc8ba)

Pressing space twice at this point clears the 'ghost' travelers and it will play as intended.

**Data to replicate**
[Start point bug.zip](https://github.com/Nornec/Midinous-Issues/files/12043529/Start.point.bug.zip)
Saved in zip because github doesn't allow uploading json files to issues for some reason

**Comment by Nornec** [comment]
Confirmed! Very strange bug -- will investigate.

**Comment by Nornec** [comment]
Should be fixed in 1.1.6.8
