### ISSUE TITLE
1.1.6.5 A point triggered before its duration ends stops sending 'High' to connected logic points once the initial duration ends.

### ISSUE THREAD

**Issue by MHGray** [Nornec/Midinous-Issues#48]
![image](https://github.com/Nornec/Midinous-Issues/assets/8196735/44d5709b-9e6f-4efb-8961-dc1db8179b07)
In the image above you can see that the grey note point on the right has been triggered (the 'clock' animation is visible) but that the attached path to the logic point isn't 'High'. It will initially activate but once the initial 8 beat duration ends it no longer sends the 'High' signal. If the duration is lowered to just below how often it is triggered, then it functions as intended, so it is something to do with being retriggered while the first trigger is still resolving.

Reproduce:
Use saved data below -> Press Play
[Logic Point bug.zip](https://github.com/Nornec/Midinous-Issues/files/12059945/Logic.Point.bug.zip)

**Comment by Nornec** [comment]
Confirmed. Will look into the logic output code for points.

**Comment by Nornec** [comment]
Fixed in 1.1.6.8
