### ISSUE TITLE
Crash when copying properties without point selected

### ISSUE THREAD

**Issue by jbarrett** [Nornec/Midinous-Issues#50]
Windows 10 Pro 22H2 64 bit.

Steps to reproduce:
- Open Midinous and Get Started
- Press 'C' (or your binding for Copy Point Properties)
- Crash?

 
[log_full.txt](https://github.com/Nornec/Midinous-Issues/files/12171336/log_full.txt) (I still have that FaceRig driver installed?!)

Thanks!

**Comment by Nornec** [comment]
Wow! how did I not account for this? Thanks. Reproduced, definite bug.

**Comment by Nornec** [comment]
Fixed in 1.1.7.0

**Comment by jbarrett** [comment]
Great stuff - thank you, Jae!
