### ISSUE TITLE
Relative values behaving strangely (depending on scale)

### ISSUE THREAD

**Issue by hjfreyer** [Nornec/Midinous-Issues#51]
I can't actually tell what version I'm on - is that listed somewhere? Steam says Build ID 11721131

Steps to reproduce:
- Set the document scale to C Ionian
- Create three notes, and connect them in a cycle
- Select the 2nd note, and choose "relative passthrough" (the arrow) on the "Note" property under "Relative Changes"
- Press play

Expected result: 3C plays 3 times.

Actual result: 3C plays, then 2B, then 3C.

However: if I change the 2nd note's "Root" under "Relative Changes" from "(none)" to "C", I get the expected result: 3 3Cs. 

I though the document scale was supposed to cascade down to all the notes, by default, so I don't really get what's going on.

**Comment by Nornec** [comment]
I would like to know if this is still a problem. When the program is still running, please look in the top right for the version number. It will be something like: "Release - 1.1.7.0"
If it is, please respond here. I haven't heard similar issues from others since this issue was opened.

**Comment by Nornec** [comment]
No update to issue given. Closing for now.
