### ISSUE TITLE
Version Version 1.1.7.0  installs the Version 1.1.6.8 Help file 

### ISSUE THREAD

**Issue by Ajakei** [Nornec/Midinous-Issues#52]
Hi I installed the demo which I think had the 1.1.7.0 help file, I'm not 100% sure. 
Then I uninstalled the demo and installed the paid version, and it has the 1.1.6.8 help file.  Easily fixed by downloading current version, just letting you know.
Note: I never installed the previous version. I only discovered Midinous yesterday.

**Comment by Nornec** [comment]
Oh shoot!! You are spot on with that. Thank you for telling me. I will resolve this soon.

-------- Original Message --------

**Comment by Nornec** [comment]
Fixed in 1.2.0.0
