### ISSUE TITLE
Small issue when entering numeric values to the end amount in slew mode in cc's

### ISSUE THREAD

**Issue by ScreenPlane** [Nornec/Midinous-Issues#53]
It's not a big thing all all, but when you are entering a 3 digit value to the end amount in slew mode of the ccs, the second and the third digit are flipped. Nothing big, just to let you know. Please see clip attached. 

https://github.com/Nornec/Midinous-Issues/assets/127771436/d1aef3dd-bc53-47d4-83aa-ff9d6c910a20

**Comment by Nornec** [comment]
Cheers for that! I'll make a note to fix this in the upcoming version.

**Comment by Nornec** [comment]
Fixed in 1.2.0.1
