### ISSUE TITLE
midinous doenst start on windows 10

### ISSUE THREAD

**Issue by Rman-nl** [Nornec/Midinous-Issues#57]
see title:
log:
[log.txt](https://github.com/Nornec/Midinous-Issues/files/15050972/log.txt)

**Comment by Nornec** [comment]
Hi there, can you try this with the new 1.2.0.0 update and see if it still is a problem?

**Comment by Rman-nl** [comment]
Midinous works without the New update.

⁣BlueMail voor Android downloaden ​

Op 4 mei 2024 01:08, om 01:08, Jae ***@***.***> schreef:
