### ISSUE TITLE
1.0.5 - Program crashing when placing a point after a load

### ISSUE THREAD

**Issue by Nornec** [Nornec/Midinous-Issues#6]
This appears to only happen when loading projects that were made in old versions. Example, loading the old demo site project works but crashes when placing points. Loading Syncopate breaks, just like tutorial.

**Comment by Nornec** [comment]
Digging into the logs, it appears this is happening because point IDs aren't being set or loaded correctly. Need to investigate how the json is loaded/converted and what the IDs are for different saves when loading in. Both old and modern.

**Comment by Rman-nl** [comment]
se issue here
[log_error.txt](https://github.com/Nornec/Midinous-Issues/files/9780832/log_error.txt)
