### ISSUE TITLE
Tooltip width is incorrect if a relative property is active [Rv]

### ISSUE THREAD

**Issue by bunxen** [Nornec/Midinous-Issues#60]
As the title says

![2024-05-13 15_09_39-Midinous - beeepp _](https://github.com/Nornec/Midinous-Issues/assets/34599433/d61469c1-922a-4428-b0dd-763b146a3cde)
![2024-05-13 15_09_22-Midinous - beeepp _](https://github.com/Nornec/Midinous-Issues/assets/34599433/9c83c57c-ee46-4d22-8bf4-52686814137e)

**Comment by Nornec** [comment]
Thank you for this. Will work on a solution.

**Comment by Nornec** [comment]
Fixed in 1.2.1.0
