### ISSUE TITLE
Ctrl + Key bindings overwrite regular bindings in case of conflict

### ISSUE THREAD

**Issue by bunxen** [Nornec/Midinous-Issues#62]
I'm on azerty keyboard, after setting A instead of Q for "Select tool" and Z for "Place tool", it removed the Ctrl+A option for "Select All" and "Undo"

**Comment by Nornec** [comment]
Will investigate. I use colemak but haven't experienced this.

**Comment by Nornec** [comment]
Fixed in 1.2.1.0
