### ISSUE TITLE
Workspace not rendering at all

### ISSUE THREAD

**Issue by steryo** [Nornec/Midinous-Issues#63]
I can't edit or produce anything because the workspace looks entirely empty when I launch the app. Toolbox and menu buttons appear but can't see the grid nor the notes. 

Tried to replicate the same issue on 1.1.7.0 but it works smoothly. Using M1 macbook, might be a metal api issue.

**Comment by Nornec** [comment]
Is this happening on 1.2.0.1? Try deleting your user settings file (click local files from the main menu) and then restarting the program. Midinous does not use Metal.

-------- Original Message --------

**Comment by steryo** [comment]
Deleting user settings solved the issue, thanks!

**Comment by Nornec** [comment]
Can you verify your app version for me please

**Comment by steryo** [comment]
Yes it was on 1.2.0.1

**Comment by Nornec** [comment]
Thanks, I will get this fixed in the next update.

**Comment by bensherman** [comment]
I am hitting this too, here is a clue - x and y coords are 32bit min and max:



![Image](https://github.com/user-attachments/assets/9488c8fe-64f8-4c2c-a363-eadd2fe259bf)

**Comment by Nornec** [comment]
Likely fixed in 1.2.1.0
