### ISSUE TITLE
crash if no note or cc has id 0

### ISSUE THREAD

**Issue by kmoulins** [Nornec/Midinous-Issues#64]
cause of the crash: no note/cc with id 0 when start is clicked

the steps to reproduce the crash:
-new file
-create a logic node, or a cc/note and delete it
-create a note
-make it a start
-click play.

note that saving after the node with id 0 is deleted soft-corrupts the file and it will make midinous crash unless a note or cc with id 0 is created manually.

temporary solution to fix the save : 
remove all connections from the start, 
name it something easy to find (e.g. test123), 
save, 
open the savefile, 
search for the name, it should look something like this : \"id\":309,\"label\":\"test123\", 
change the number (309) next to id to 0.

**Comment by Nornec** [comment]
Thank you for the formal report. Working on it.

**Comment by Nornec** [comment]
Likely fixed in 1.2.1.0
