### ISSUE TITLE
1.0.5 Inconsistency between Midinous application icon and its shortcut icon

### ISSUE THREAD

**Issue by worblyhead** [Nornec/Midinous-Issues#7]
When installing Midinous on my Win10 machine I also had Steam create a Desktop shortcut.  However, I noticed that the Icon used in the application (upper left corner of the Midinous window) and the icon used for the desktop shortcut are not the same

1) Install the Midinous 1.0.5 version and have Steam create a desktop icon
2) Open the Midinous app and NOTE that the icon in the upper left corner and the icon used for the Shortcut are not the same.

Not that it matters here per se, but the desktop shortcut icon is the same one used for the Midinous Discord server.  
<img width="1152" alt="Midinous_Icons" src="https://user-images.githubusercontent.com/115739648/195704337-5ea503e8-a7a0-405c-b183-0562085b7a67.png">

**Comment by Nornec** [comment]
There's nothing i can do about this. It is an artifact of the Monogame framework (for which Midinous is built) that cannot be changed on Windows.

**Comment by worblyhead** [comment]
Ahhh, so the icon in the app itself is Monogame?  I thought the stylized "M" icon was an update to the Midinous icon. Yeah, it kind of is a pain when frameworks don't give control of this sort of thing to external developers.
