### ISSUE TITLE
1.0.5 Midinous UI can be closed while still in a dirty state and thus resulting in lost work

### ISSUE THREAD

**Issue by worblyhead** [Nornec/Midinous-Issues#9]
If I do work in Midinous resulting in a dirty state (i.e. unsaved changes), I get an expected Unsaved Changes nag dialog if I attempt to start a New session or load another session.  However, if I simply close the dialog using the 'X' control in the upper right corner while in a dirty state then the UI simply closes resulting in lost work

1) Open a new Midinous session or load an existing session.
2) Make a small change resulting in a dirty state ('*' appears in the title bar)
3) Open a New or existing session and NOTE that an Unsaved Changes dialog opens as expected.
4) Without clicking anything else simply close the UI using the controls in the upper right of the UI window.
5) NOTE, the UI closes without any of my changes being saved
6) Another Variation is simply to put the UI into a dirty state and click the 'X' UI control button to close the UI.

Not sure what your philosophy is here Jay regarding this behavior, but this is a common User workflow (inadvertent or not).  Getting into solution space here, but would it be possible to make the Unsaved Changes dialog a blocking modal window such that the UI will/can not shut down with the changes being saved?

<img width="850" alt="Midinous_UnsavedChanges_1" src="https://user-images.githubusercontent.com/115739648/195731784-f3164ab7-7eae-44c0-933c-8ccebb028db5.png">

**Comment by Nornec** [comment]
There is nothing I can do about this currently. This is another Monogame annoyance -- I cannot capture the window events, but can capture Alt-F4, and other keystrokes, surprisingly. Though I agree with your philosophy, I have no plans to fix this in coming releases.
